"""Add session column to Course

Revision ID: 48de013af6cf
Revises: b2a617aa473b
Create Date: 2025-10-10 10:44:58.652687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48de013af6cf'
down_revision = 'b2a617aa473b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', sa.String(length=20), nullable=True))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('session')

    # ### end Alembic commands ###
