"""Add upload_time to course_material

Revision ID: 7258e7091fe0
Revises: a94afc66ceaa
Create Date: 2025-10-10 14:01:17.906368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7258e7091fe0'
down_revision = 'a94afc66ceaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_code_per_session'), type_='unique')

    with op.batch_alter_table('course_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('filetype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filetype', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('upload_time')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_code_per_session'), ['code', 'session'])

    # ### end Alembic commands ###
