"""Add session to course_material

Revision ID: 8ac0443aa247
Revises: 7258e7091fe0
Create Date: 2025-10-10 14:07:27.295040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac0443aa247'
down_revision = '7258e7091fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_material', schema=None) as batch_op:
        batch_op.drop_column('session')

    # ### end Alembic commands ###
