"""Add session field to Course

Revision ID: c37a61e2a7f4
Revises: 6d2fed42c822
Create Date: 2025-10-10 10:32:58.252495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37a61e2a7f4'
down_revision = '6d2fed42c822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', sa.String(length=20), nullable=False))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('session')

    # ### end Alembic commands ###
